spring.application.name=busReserve

# === DataSource (PostgreSQL) ===
spring.datasource.url=jdbc:postgresql://localhost:5432/busReserve
spring.datasource.username=postgres
spring.datasource.password=1082876634
security.jwt.secret=supersecuresecretkeyforjwtauth123


# === JPA / Hibernate ===
# MUY IMPORTANTE: deja el esquema a cargo de Flyway
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

